### ISSUE TITLE
Status code 429 

### ISSUE THREAD

**Issue by davids-laughter** [somritdasgupta/hypebard#7]
When I type in the search box of the app it's giving me an error code 429 and saying I need to update billing?

**Comment by somritdasgupta** [comment]
Hey there,

I noticed you're experiencing an API call limit issue with your app Hypebard, which is based on the OpenAI GPT API. The error code 429 indicates that you have reached the limit for the free trial phase grant.

To address this, I've added a new feature to Hypebard that allows users to use their own OpenAI GPT API key. This way, they can generate their own secret API key by visiting the OpenAI API platform at https://platform.openai.com/account/api-keys. Once they have their API key, they can easily enter it in the Hypebard settings under the "Custom OpenAI API key" option.

By using their own API key, users will be able to bypass the trial phase limit and continue enjoying the full functionality of Hypebard without any interruptions.

I hope this helps!
